### PR TITLE
fix the gem spec and readme

### PR DESCRIPTION
**Pull request by rubydesign**
include the grammar files
fix the instructions
clarify about load and require
and make require return what load returned, so the instructions make
more sense

### CODE REVIEW

**Comment by dancinglightning** [comment]
This fixes #52 as far as i can tell

**Comment by dancinglightning** [comment]
Ok, sorry. I really didn't want to step on your toes there by changing that.

My choice was to change the code or change the docs. My reasoning was that since you wrote the docs (with load), someone else wrote the require and didn't update the docs. So that change i made was to reduce impact on the docs only.

Are you otherwise ok? I can change the require back as it was and then update the docs accordingly. Meaning i don't have strong feelings which way this goes, i just like to help with making the docs right.

btw: Great work. I have used both treetop and parslet and this strikes what i find a perfect balance: In treetop i never understood why it would have to generate code, when ruby lets you do that just fine. And in parslet (which has no grammar only an api) the "restriction" to ruby makes the grammar less concise.

If you want something else done, i'd be happy to help some more.

**Comment by dancinglightning** [comment]
I hope the question was clear enough in there: do you want me to change the require back ?

**Comment by dancinglightning** [comment]
hi @mjackson 
not quite sure how to proceed here ?

**Comment by blambeau** [comment]
@dancinglightning I think it's better to let the behavior of the code unchanged and fix the documentation instead. No one ever complained about `require` as it was.

P.S. My experience told me that, sometimes, pinging @mjackson on twitter may help getting an answer. Github's notification system should probably be improved.

**Comment by dancinglightning** [comment]
hi @blambeau thanks for the tip.
As i was "just" trying to fix the docs, something had to be done. At least the docs are right and it seems to me in the spirit of things.
So i will wait and see what @mjackson says. I'm not on twitter.

**Comment by phreakocious** [comment]
Will this ever be merged?  The broken gemspec means that none of the included grammar is functional.

**Pull request closed without merging**
